/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author T430
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        initComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        MensajeDeTipoDeHelado = new javax.swing.JLabel();
        radioTipoCucurucho = new javax.swing.JRadioButton();
        radioTipoVasito = new javax.swing.JRadioButton();
        radioTipoCuarto = new javax.swing.JRadioButton();
        radioTipoMedio = new javax.swing.JRadioButton();
        radioTipoKilo = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        comboCantidadDeGustos = new javax.swing.JComboBox<>();
        checkBaniadoChocolate = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        botonVer = new javax.swing.JButton();
        labelVer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo De Helado"));

        MensajeDeTipoDeHelado.setText("Ingrese el tipo de helado que quiere");

        buttonGroup1.add(radioTipoCucurucho);
        radioTipoCucurucho.setText("Cucurucho");
        radioTipoCucurucho.setActionCommand("Cucurucho");
        radioTipoCucurucho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTipoCucuruchoActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioTipoVasito);
        radioTipoVasito.setText("Vasito");
        radioTipoVasito.setActionCommand("Vasito");
        radioTipoVasito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTipoVasitoActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioTipoCuarto);
        radioTipoCuarto.setText("1/4 Kg");
        radioTipoCuarto.setActionCommand("1/4 Kg");
        radioTipoCuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTipoCuartoActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioTipoMedio);
        radioTipoMedio.setText("1/2Kg");
        radioTipoMedio.setActionCommand("1/2Kg");
        radioTipoMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTipoMedioActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioTipoKilo);
        radioTipoKilo.setText("1 Kg");
        radioTipoKilo.setActionCommand("1 Kg");
        radioTipoKilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTipoKiloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MensajeDeTipoDeHelado)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioTipoCucurucho)
                            .addComponent(radioTipoVasito))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioTipoMedio)
                            .addComponent(radioTipoCuarto)
                            .addComponent(radioTipoKilo))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MensajeDeTipoDeHelado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioTipoCucurucho)
                    .addComponent(radioTipoCuarto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioTipoVasito)
                    .addComponent(radioTipoMedio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioTipoKilo))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad de Gustos"));

        comboCantidadDeGustos.setName(""); // NOI18N
        comboCantidadDeGustos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCantidadDeGustosActionPerformed(evt);
            }
        });

        checkBaniadoChocolate.setText("Bañado en Chocolate");
        checkBaniadoChocolate.setEnabled(false);
        checkBaniadoChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBaniadoChocolateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(checkBaniadoChocolate)
                        .addGap(0, 120, Short.MAX_VALUE))
                    .addComponent(comboCantidadDeGustos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(comboCantidadDeGustos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(checkBaniadoChocolate)
                .addContainerGap())
        );

        botonVer.setText("ver seleccion");
        botonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(botonVer)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(botonVer)
                .addGap(0, 58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(labelVer, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelVer, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioTipoVasitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTipoVasitoActionPerformed
        disableBaniado();
        fillComboCantidadGustos(2);
    }//GEN-LAST:event_radioTipoVasitoActionPerformed

    private void radioTipoCuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTipoCuartoActionPerformed
        disableBaniado();
        fillComboCantidadGustos(2);
    }//GEN-LAST:event_radioTipoCuartoActionPerformed

    private void radioTipoMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTipoMedioActionPerformed
        disableBaniado();
        fillComboCantidadGustos(3);
    }//GEN-LAST:event_radioTipoMedioActionPerformed

    private void radioTipoKiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTipoKiloActionPerformed
        disableBaniado();
        fillComboCantidadGustos(4);
    }//GEN-LAST:event_radioTipoKiloActionPerformed

    private void comboCantidadDeGustosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCantidadDeGustosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCantidadDeGustosActionPerformed

    private void checkBaniadoChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBaniadoChocolateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBaniadoChocolateActionPerformed

    private void radioTipoCucuruchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTipoCucuruchoActionPerformed
        enabledBaniado();
        fillComboCantidadGustos(2);
    }//GEN-LAST:event_radioTipoCucuruchoActionPerformed

    private void botonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerActionPerformed
        String radioSeleccionado = buttonGroup1.getSelection().getActionCommand();
        
        String comboSeleccionado = comboCantidadDeGustos.getSelectedItem().toString();
        
        
        labelVer.setText("Radio: " + radioSeleccionado + " Combo: " + comboSeleccionado);
        
    }//GEN-LAST:event_botonVerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MensajeDeTipoDeHelado;
    private javax.swing.JButton botonVer;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkBaniadoChocolate;
    private javax.swing.JComboBox<String> comboCantidadDeGustos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelVer;
    private javax.swing.JRadioButton radioTipoCuarto;
    private javax.swing.JRadioButton radioTipoCucurucho;
    private javax.swing.JRadioButton radioTipoKilo;
    private javax.swing.JRadioButton radioTipoMedio;
    private javax.swing.JRadioButton radioTipoVasito;
    // End of variables declaration//GEN-END:variables

    private void initComboBox() {

        DefaultComboBoxModel modelo = new DefaultComboBoxModel<>();
        modelo.addElement("Cantidad de gustos sin definir");
        
        comboCantidadDeGustos.setModel(modelo);
    }

    private void disableBaniado() {
        checkBaniadoChocolate.setEnabled(false);
        checkBaniadoChocolate.setSelected(false);
    }

    private void enabledBaniado() {
        checkBaniadoChocolate.setEnabled(true);
    }

    private void fillComboCantidadGustos(int cantidad) {
        comboCantidadDeGustos.removeAllItems();
        
        DefaultComboBoxModel modeloCucurucho = new DefaultComboBoxModel<>();
        
        if (cantidad == 2){
            modeloCucurucho.addElement("1 gusto");
            modeloCucurucho.addElement("2 gusto");
        }
        
        if (cantidad == 3){
            modeloCucurucho.addElement("1 gusto");
            modeloCucurucho.addElement("2 gusto");
            modeloCucurucho.addElement("3 gusto");
        }
        
        if (cantidad == 4){
            modeloCucurucho.addElement("1 gusto");
            modeloCucurucho.addElement("2 gusto");
            modeloCucurucho.addElement("3 gusto");
            modeloCucurucho.addElement("4 gusto");
        }
        comboCantidadDeGustos.setModel(modeloCucurucho);
    }
    
}
